// <auto-generated />
namespace SpaceMuseum.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix201612210534 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix201612210534));
        
        string IMigrationMetadata.Id
        {
            get { return "201612210334151_fix201612210534"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
